encoder_base:
  _target_: efficientnet_pytorch.EfficientNet.from_name
  model_name: efficientnet-b4
  num_classes: 2
head:
  _fc:
  - _target_: torch.nn.Linear
    in_features: 1792
    out_features: 2
    bias: true